name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 3.1.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build Smart Fleet Management Services
        run: dotnet build ./SmartFleetManagement.Services --configuration Release
